quarkus:
  application:
    name: cfp-aggregator

  # Qute
  qute:
    suffixes:
      - html
      - txt
      - yml
      - yaml
      - properties
      - sql
      - cfpimport
    content-types:
      yml: application/yaml
      yaml: application/yaml
      properties: text/properties
      sql: application/sql
      cfpimport: application/cfp-import

  # Flyway
  flyway:
    migrate-at-start: true
    baseline-version: 1.0.0
    baseline-description: Initial version

  # Jackson
  jackson:
    serialization-inclusion: non-empty

  # HTTP
  http:
    cors:
      enabled: true
      origins: '*'
    test-port: 0
  dev-ui:
    cors:
      enabled: true
  tls:
    trust-all: true

  # Rest config
  rest:
    jackson:
      optimization:
        enable-reflection-free-serializers: true

  # Datasource
  datasource:
    jdbc:
      telemetry: true
      url: jdbc:h2:mem:portals
    username: cfp
    password: cfp

  # Hibernate
  hibernate-orm:
    sql-load-script: no-file
    schema-management:
      strategy: validate
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    metrics:
      enabled: true
    dev-ui:
      allow-hql: true

  # OpenTelemetry and tracing
  otel:
    logs:
      enabled: true
    metrics:
      enabled: true

# Dev and test modes config
'%dev,test':
#  cfps:
#    log-requests: true
#    log-responses: true
#    reload-on-startup: true
#    portals:
#      jl4ktls0:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: sessionize
#        description: Sessionize test portal
#      devoxxuk2025:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Devoxx UK 2025
#      devoxxpl25:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Devoxx Poland 2025
#      voxxedlu2025:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Voxxed Days Luxembourg 2025
#      devoxxfr2025:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Devoxx France 2025
#      dvgr25:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Devoxx Greece 2025
#      vdams25:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Voxxed Days Amsterdam 2025
#      vdbuh2025:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Voxxed Days Bucharest 2025
#      dvbe25:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Devoxx Belgium 2025
#      dvma25:
#        base-url: http://localhost:${quarkus.wiremock.devservices.port}
#        portal-type: cfp-dev
#        description: Devoxx Morocco 2025

  quarkus:
    observability:
      enabled: false
    micrometer:
      export:
        otlp:
          enabled: "${%test.quarkus.observability.enabled}"
    log:
      category:
        'com.redhat':
          level: DEBUG
        'io.quarkiverse.wiremock.devservice.WireMockServer':
          level: WARN
      console:
        level: DEBUG
    flyway:
      clean-at-start: true
    wiremock:
      devservices:
        files-mapping: src/test/resources/wiremock

# test mode config
'%test':
  quarkus:
    log:
      category:
        "io.quarkiverse.wiremock.devservice.WireMockServer":
          level: ERROR
    wiremock:
      devservices:
        enabled: true
    otel:
      logs:
        enabled: false
    observability:
      enabled: false
    micrometer:
      export:
        otlp:
          enabled: "${%test.quarkus.observability.enabled}"
  cfps:
    reload-on-startup: false
    portals:
      jl4ktls0:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: sessionize
        description: Sessionize test portal
      devoxxuk2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx UK 2025
      devoxxpl25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Poland 2025
      voxxedlu2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Voxxed Days Luxembourg 2025
      devoxxfr2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx France 2025
      dvgr25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Greece 2025
      vdams25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Voxxed Days Amsterdam 2025
      vdbuh2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Voxxed Days Bucharest 2025
      dvbe25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Belgium 2025
      dvma25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Morocco 2025

'%dev':
  quarkus:
    hibernate-orm:
      log:
        sql: true
    datasource:
      dev-ui:
        allow-sql: true
