cfps:
  portals:
    devoxxuk2025:
      base-url: https://devoxxuk25.cfp.dev
      portal-type: cfp-dev
      description: Devoxx UK 2025
    devoxxpl25:
      base-url: https://devoxxpl25.cfp.dev
      portal-type: cfp-dev
      description: Devoxx Poland 2025
  reload-on-startup: true
  log-requests: true
  log-responses: true

quarkus:
  # Flyway
  flyway:
#    baseline-at-start: true
#    baseline-on-migrate: true
#    migrate-at-start: true
    baseline-version: 1.0.0
    baseline-description: Initial version

  # Jackson
  jackson:
    serialization-inclusion: non-empty

  # HTTP
  http:
    cors:
      enabled: true
      origins: '*'
  dev-ui:
    cors:
      enabled: true
  tls:
    trust-all: true

  # Hibernate
  hibernate-orm:
    sql-load-script: no-file
    schema-management:
      strategy: drop-and-create
#      strategy: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    metrics:
      enabled: true
    dev-ui:
      allow-hql: true

  # OpenTelemetry and tracing
  otel:
    logs:
      enabled: true
    metrics:
      enabled: true
  datasource:
    jdbc:
      telemetry: true

  # Wiremock
  wiremock:
    devservices:
      enabled: false

# Dev and test modes config
'%dev,test':
  quarkus:
    otel:
      logs:
        enabled: false
    observability:
      enabled: false
    micrometer:
      export:
        otlp:
          enabled: "${%test.quarkus.observability.enabled}"
    log:
      category:
        'com.redhat':
          level: DEBUG
      console:
        level: DEBUG
    flyway:
      clean-at-start: true

# test mode config
'%test':
  quarkus:
    log:
      category:
        "io.quarkiverse.wiremock.devservice.WireMockServer":
          level: ERROR
    wiremock:
      devservices:
        enabled: true
    otel:
      logs:
        enabled: false
    observability:
      enabled: false
    micrometer:
      export:
        otlp:
          enabled: "${%test.quarkus.observability.enabled}"
  cfps:
    reload-on-startup: false

'%dev':
  quarkus:
    hibernate-orm:
      log:
        sql: true
    datasource:
      dev-ui:
        allow-sql: true