cfps:
  portals:
    devoxxuk2025:
      base-url: https://devoxxuk25.cfp.dev
      portal-type: cfp-dev
      description: Devoxx UK 2025
    devoxxpl25:
      base-url: https://devoxxpl25.cfp.dev
      portal-type: cfp-dev
      description: Devoxx Poland 2025
    voxxedlu2025:
      base-url: https://voxxedlu2025.cfp.dev
      portal-type: cfp-dev
      description: Voxxed Days Luxembourg 2025
    devoxxfr2025:
      base-url: https://devoxxfr2025.cfp.dev
      portal-type: cfp-dev
      description: Devoxx France 2025
    dvgr25:
      base-url: https://dvgr25.cfp.dev
      portal-type: cfp-dev
      description: Devoxx Greece 2025
    vdams25:
      base-url: https://vdams25.cfp.dev
      portal-type: cfp-dev
      description: Voxxed Days Amsterdam 2025
    vdbuh2025:
      base-url: https://vdbuh2025.cfp.dev
      portal-type: cfp-dev
      description: Voxxed Days Bucharest 2025
    dvbe25:
      base-url: https://dvbe25.cfp.dev
      portal-type: cfp-dev
      description: Devoxx Belgium 2025
    dvma25:
      base-url: https://dvma25.cfp.dev
      portal-type: cfp-dev
      description: Devoxx Morocco 2025
  reload-on-startup: true
  log-requests: true
  log-responses: true

quarkus:
  application:
    name: cfp-aggregator

  # Flyway
  flyway:
#    baseline-at-start: true
#    baseline-on-migrate: true
#    migrate-at-start: true
    baseline-version: 1.0.0
    baseline-description: Initial version

  # Jackson
  jackson:
    serialization-inclusion: non-empty

  # HTTP
  http:
    cors:
      enabled: true
      origins: '*'
    test-port: 0
  dev-ui:
    cors:
      enabled: true
  tls:
    trust-all: true

  # Rest config
  rest:
    jackson:
      optimization:
        enable-reflection-free-serializers: true

  # Hibernate
  hibernate-orm:
    sql-load-script: no-file
    schema-management:
      strategy: drop-and-create
#      strategy: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    metrics:
      enabled: true
    dev-ui:
      allow-hql: true

  # OpenTelemetry and tracing
  otel:
    logs:
      enabled: true
    metrics:
      enabled: true
  datasource:
    jdbc:
      telemetry: true

# Dev and test modes config
'%dev,test':
  cfps:
    portals:
      devoxxuk2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx UK 2025
      devoxxpl25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Poland 2025
      voxxedlu2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Voxxed Days Luxembourg 2025
      devoxxfr2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx France 2025
      dvgr25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Greece 2025
      vdams25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Voxxed Days Amsterdam 2025
      vdbuh2025:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Voxxed Days Bucharest 2025
      dvbe25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Belgium 2025
      dvma25:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
        portal-type: cfp-dev
        description: Devoxx Morocco 2025

  quarkus:
    observability:
      enabled: false
    micrometer:
      export:
        otlp:
          enabled: "${%test.quarkus.observability.enabled}"
    log:
      category:
        'com.redhat':
          level: DEBUG
        'io.quarkiverse.wiremock.devservice.WireMockServer':
          level: WARN
      console:
        level: DEBUG
    flyway:
      clean-at-start: true
    wiremock:
      devservices:
        files-mapping: src/test/resources/wiremock

# test mode config
'%test':
  quarkus:
    log:
      category:
        "io.quarkiverse.wiremock.devservice.WireMockServer":
          level: ERROR
    wiremock:
      devservices:
        enabled: true
    otel:
      logs:
        enabled: false
    observability:
      enabled: false
    micrometer:
      export:
        otlp:
          enabled: "${%test.quarkus.observability.enabled}"
  cfps:
    reload-on-startup: false

'%dev':
  quarkus:
    hibernate-orm:
      log:
        sql: true
    datasource:
      dev-ui:
        allow-sql: true